### ISSUE TITLE
Ability to link directly to a generated SVG/PNG

### ISSUE THREAD

**Issue by Shpigford** [fangpenlin/avataaars#2]
The ability to download a generated SVG or PNG is great, but I'd love to be able to link directly to the SVG or PNG file.

Use case here is generating random avatars for user profiles on a web app.

Basically want to use this app as an API server for generating these and then link to randomly generated images.

```
example.com/?accessoriesType=Prescription01&avatarStyle=Transparent&clotheColor=Blue01&clotheType=BlazerShirt&eyeType=Hearts&eyebrowType=SadConcerned&facialHairColor=Black&facialHairType=BeardLight&graphicType=Resist&hairColor=Black&mouthType=Smile&skinColor=Light&topType=LongHairMiaWallace.svg
```

(Note the added `.svg` on the end of the URL)

**Comment by gkoberger** [comment]
For anyone else who wants this, you can use https://avataaars.io for it. Just use the query strings from getavataaars.com:

    <img src="https://avataaars.io/?accessoriesType=Prescription01&avatarStyle=Circle&clotheType=Hoodie&eyeType=EyeRoll&eyebrowType=UnibrowNatural&facialHairType=BeardLight&hairColor=Black&mouthType=Eating&skinColor=Yellow&topType=LongHairShavedSides">

<img src="https://avataaars.io/?accessoriesType=Prescription01&avatarStyle=Circle&clotheType=Hoodie&eyeType=EyeRoll&eyebrowType=UnibrowNatural&facialHairType=BeardLight&hairColor=Black&mouthType=Eating&skinColor=Yellow&topType=LongHairShavedSides">

**Comment by wpitallo** [comment]
Any idea what the source code for https://avataaars.io/ is doing? Would be great if this was available as well

**Comment by birdycn** [comment]
thanks

**Comment by gkoberger** [comment]
@wpitallo here ya go: https://github.com/gkoberger/avataaars

Basically, just rendering react on the server

**Comment by nosovsh** [comment]
@gkoberger thanks for the possibility to use it directly via link in img. How safe is it to use on my website (no highload in any way)? I mean do you plan to keep this server alive or is it better to save images after generation?

**Comment by gkoberger** [comment]
@nosovsh it seems pretty simple to run, so I expect it to be pretty safe to direct link to! I plan on just leaving it up forever (it runs on a $7 heroku instance, so I'm not worried)

**Comment by wpitallo** [comment]
Awesome thank you! @gkoberger

**Comment by levi0214** [comment]
Awesome！ @gkoberger

**Comment by clementdevos** [comment]
It's been down once, could you open source your code so we can host it for us? 

Cheers,

**Comment by Shpigford** [comment]
@clementdevos https://github.com/gkoberger/avataaars
