### ISSUE TITLE
How to add custom components?

### ISSUE THREAD

**Issue by michael-badrobotgames** [fangpenlin/avataaars#24]
Hello,

I'm wondering what the workflow is for adding additional components to this system. I've got the original Avatar Library open in Sketch, but I'm not clear on how to export components into the React Component format used to store the individual elements in this project. Any help would be greatly appreciated!!! Thanks for making this, it's awesome!

**Comment by mpseidel** [comment]
Wondering the same. Would love to be a able to add custom pieces.

Looks like the current design has no hooks to do that though?

**Comment by clementdevos** [comment]
We ended up forking the app to add our own SVG for the logo shirt.

**Comment by fangpenlin** [comment]
You can use Sketch, right click on the component you want to export, click "Copy SVG". Then paste into the HTML file I created here

https://github.com/fangpenlin/avataaars-generator/blob/master/tools/component-extractor.html

to make it generate the corresponding react component for you. It's not 100% automatic process, some manual adjustments still need to be done, but could save you some time convert all these stuff one by one.

**Comment by michael-badrobotgames** [comment]
Can you clarify what you mean by pasting into that html file. I cloned the avataars-generator and got the component extractor up but I'm not sure what's supposed to happen.
<img width="989" alt="Screen Shot 2019-08-20 at 1 16 48 PM" src="https://user-images.githubusercontent.com/44276924/63381067-c87bd400-c34c-11e9-814e-c864f2f10a70.png">

**Comment by michael-badrobotgames** [comment]
That was my trying to copy the vomit mouth and paste it into the component extractor...

**Comment by michael-badrobotgames** [comment]
I've just added a new component, an open mouth to src/avatar/face/mouth as Open.tsx, and updated the mouth/index.tsx to include a reference to it. What do I do now to rebuild the project so that my new addition is included in the dist?

**Comment by michael-badrobotgames** [comment]
I'm used to seeing scripts defined in package.json but I don't see any for this project...

**Comment by michael-badrobotgames** [comment]
Alright. Apologies for being so green. Realized I needed to install typescript to compile the project - just got it working.
