### ISSUE TITLE
Warning on componentWillMount

### ISSUE THREAD

**Issue by jeremy2918** [fangpenlin/avataaars#40]
There is an error in the terminal every time an avatar is rendered. It should be easy to solve since it is just asking to change the used method. This is the error:

```bash
Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.
```

And the line it is referring to is this one: 
https://github.com/fangpenlin/avataaars/blob/e16cf0202b6d5b239d05bb565859537bd719bc1a/src/index.tsx#L42

**Comment by fangpenlin** [comment]
fixed already in master branch
