### ISSUE TITLE
ranem to UNSAFE_componentWillUpdate

### ISSUE THREAD

**Issue by chkhetiani** [fangpenlin/avataaars#43]
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: AvatarComponent, Selector

Learn more about this warning here: https://reactjs.org/link/legacy-context

**Comment by lancejpollard** [comment]
Yeah second this, is there any chance you could update this to the latest version of react? :)

<img width="886" alt="Screen Shot 2021-08-14 at 7 19 29 AM" src="https://user-images.githubusercontent.com/28718/129449356-88df183c-4505-4392-af52-e639f8da2b1b.png">

**Comment by fangpenlin** [comment]
already fixed in the master branch, will make a new release soon
